server:
  port: 8081
  
spring:
  application:
    name: fraud
  datasource:    username: springtest
    password: 1234qwer
    url: jdbc:mysql://192.168.0.30:3306/tazz0009?serverTimezone=UTC
  jpa:    hibernate:      ddl-auto: update    show-sql: true    properties:
      hibernate:        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true      
  